# configuration related to pull request comments
comment: false # do not comment PR with the result

ignore:
  - apps/
  - unittests/

parsers:
  gcov:
    branch_detection:
      conditional: false
      loop: false
      method: false
      macro: false

coverage:
  range: 20..90 # coverage lower than 20 is red, higher than 90 green, between color code

  status:
    project: # settings affecting project coverage
      default:
        target: auto # auto % coverage target
        threshold: 5%  # allow for 5% reduction of coverage without failing
