////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//   _____   ____    _   _  ____ _______   ______ _____ _____ _______ _   //
//  |  __ \ / __ \  | \ | |/ __ \__   __| |  ____|  __ \_   _|__   __| |  //
//  | |  | | |  | | |  \| | |  | | | |    | |__  | |  | || |    | |  | |  //
//  | |  | | |  | | | . ` | |  | | | |    |  __| | |  | || |    | |  | |  //
//  | |__| | |__| | | |\  | |__| | | |    | |____| |__| || |_   | |  |_|  //
//  |_____/ \____/  |_| \_|\____/  |_|    |______|_____/_____|  |_|  (_)  //
//                                                                        //
//     WARNING! This is an automatically generated file.  DO NOT EDIT     //
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

#ifndef GCUHOUSEKEEPINGPACKET_H
#define GCUHOUSEKEEPINGPACKET_H

#include <stdint.h>

struct GCUHousekeepingPacket {
  uint16_t Sync;
  uint8_t PacketID;
  uint32_t UnixTime;
  uint16_t PacketCounter;
  uint16_t PacketSize;
  uint16_t* Temp;
  uint16_t* ADC;
  uint16_t CryoTipTemp;
  uint16_t CryoPower;
  uint64_t ClkVal;
  uint8_t* LastCommandIDs;
  uint16_t* LastCommandPayloads;
  uint16_t NumGoodCommands;
  uint16_t NumBadCommands;
  uint8_t OPADataRate;
  uint8_t OPBDataRate;
  uint8_t NumAutoResyncs;
  uint8_t HeaterBoxReadBack7;
  uint8_t HeaterBoxReadBack6;
  uint8_t HeaterBoxReadBack5;
  uint8_t HeaterBoxReadBack4;
  uint8_t HeaterBoxReadBack3;
  uint8_t HeaterBoxReadBack2;
  uint8_t HeaterBoxReadBack1;
  uint8_t HeaterBoxReadBack0;
  uint16_t NumGCURestarts;
  uint32_t NumBytesInRelayQueue;
  uint8_t HeaterBoxSetting7;
  uint8_t HeaterBoxSetting6;
  uint8_t HeaterBoxSetting5;
  uint8_t HeaterBoxSetting4;
  uint8_t HeaterBoxSetting3;
  uint8_t HeaterBoxSetting2;
  uint8_t HeaterBoxSetting1;
  uint8_t HeaterBoxSetting0;
  uint8_t TStat7Enabled;
  uint8_t TStat6Enabled;
  uint8_t TStat5Enabled;
  uint8_t TStat4Enabled;
  uint8_t TStat3Enabled;
  uint8_t TStat2Enabled;
  uint8_t TStat1Enabled;
  uint8_t TStat0Enabled;
  uint8_t MagredEnabled;
  uint8_t MagredPID;
  uint8_t ClkbrdGPIO2;
  uint8_t ClkbrdGPIO1;
  uint8_t ClkbrdGPIO0;
  uint8_t MagredCounter;
  uint32_t RelayNumPacketsDropped;
  uint64_t RelayNumBytesDropped;
  uint8_t RelayRawDataEnabled;
  uint8_t RelayComptonEnabled;
  uint8_t RelayQueueAccepting;
  uint32_t LOSNumBytesInQueue;
  uint64_t LOSBytesWritten;
  uint32_t LOSNumPacketsDropped;
  uint64_t LOSNumBytesDropped;
  uint8_t LOSAutoClear;
  uint8_t LOSIsOpen;
  uint8_t LOSComptonEnabled;
  uint8_t LOSQueueAccepting;
  uint8_t LOSEnabled;
  uint32_t DiskNumBytesInQueue;
  uint64_t DiskANumBytesWritten;
  uint64_t DiskBNumBytesWritten;
  uint64_t DiskCNumBytesWritten;
  uint8_t DiskCIsMounted;
  uint8_t DiskBIsMounted;
  uint8_t DiskAIsMounted;
  uint8_t DiskCNotNull;
  uint8_t DiskBNotNull;
  uint8_t DiskANotNull;
  uint8_t DiskComptonEnabled;
  uint32_t GRBNumBytesInQueue;
  uint32_t GRBTdiff;
  uint32_t GRBNumTriggers;
  uint8_t ShieldAlgoTrigEnabled2;
  uint8_t ShieldAlgoTrigEnabled1;
  uint8_t ShieldAlgoTrigEnabled0;
  uint8_t GRBAutoTriggerEnabled;
  uint8_t GRBTriggerActive;
  uint8_t GRBQueueAccepting;
  uint32_t RTANumBytesInQueue;
  uint8_t RTAAcceptingSingleDetectorEvents;
  uint8_t RTAAutoRebootEnabled;
  uint8_t RTAComptonAnalysisEnabled;
  uint8_t RTAComptonQueueAutoClearEnabled;
  uint8_t RTAQueueAccepting;
  uint8_t RTAEnabled;
  uint64_t OpenPortANumBytesWritten;
  uint8_t UnixTimeMSB;
  uint8_t OpenPortAUDPSocket;
  uint8_t OpenPortAEnabled;
  uint64_t OpenPortBNumBytesWritten;
  uint8_t OpenPortBUDPSocket;
  uint8_t OpenPortBEnabled;
  uint8_t* NumRestartsCC;
  uint8_t SerialDialupOpen;
  uint8_t SerialCryoOpen;
  uint8_t SerialMagOpen;
  uint8_t SerialGPSOpen;
  uint8_t SerialSIP2Open;
  uint8_t SerialSIP1Open;
  uint8_t DiskAUsage;
  uint8_t DiskBUsage;
  uint8_t DiskCUsage;
  uint8_t HVStatusCC11;
  uint8_t HVStatusCC10;
  uint8_t HVStatusCC9;
  uint8_t HVStatusCC8;
  uint8_t HVStatusCC7;
  uint8_t HVStatusCC6;
  uint8_t HVStatusCC5;
  uint8_t HVStatusCC4;
  uint8_t HVStatusCC3;
  uint8_t HVStatusCC2;
  uint8_t HVStatusCC1;
  uint8_t HVStatusCC0;
  uint8_t HVStatusShield5;
  uint8_t HVStatusShield4;
  uint8_t HVStatusShield3;
  uint8_t HVStatusShield2;
  uint8_t HVStatusShield1;
  uint8_t HVStatusShield0;
  uint8_t* ShieldThreshold;
  uint8_t DiskCEnabled;
  uint8_t DiskBEnabled;
  uint8_t DiskAEnabled;
  uint8_t GlobalClockSupervisorResyncEnabled;
  uint8_t GPSMagEnabled;
  uint8_t GPSEnabled;
  uint8_t EthernetReallocateEnabled;
  uint8_t GlobalPROMLoadSuccessful;
  uint8_t RTAContinuityOK7;
  uint8_t RTAContinuityOK6;
  uint8_t RTAContinuityOK5;
  uint8_t RTAContinuityOK4;
  uint8_t RTAContinuityOK3;
  uint8_t RTAContinuityOK2;
  uint8_t RTAContinuityOK1;
  uint8_t RTAContinuityOK0;
  uint8_t GlobalSyncStatusCC3;
  uint8_t GlobalSyncStatusCC2;
  uint8_t GlobalSyncStatusCC1;
  uint8_t GlobalSyncStatusCC0;
  uint8_t RTAContinuityOK11;
  uint8_t RTAContinuityOK10;
  uint8_t RTAContinuityOK9;
  uint8_t RTAContinuityOK8;
  uint8_t GlobalSyncStatusCC11;
  uint8_t GlobalSyncStatusCC10;
  uint8_t GlobalSyncStatusCC9;
  uint8_t GlobalSyncStatusCC8;
  uint8_t GlobalSyncStatusCC7;
  uint8_t GlobalSyncStatusCC6;
  uint8_t GlobalSyncStatusCC5;
  uint8_t GlobalSyncStatusCC4;
  uint8_t RTANumEventsActive7;
  uint8_t RTANumEventsActive6;
  uint8_t RTANumEventsActive5;
  uint8_t RTANumEventsActive4;
  uint8_t RTANumEventsActive3;
  uint8_t RTANumEventsActive2;
  uint8_t RTANumEventsActive1;
  uint8_t RTANumEventsActive0;
  uint8_t RTAAnalysisEnabled3;
  uint8_t RTAAnalysisEnabled2;
  uint8_t RTAAnalysisEnabled1;
  uint8_t RTAAnalysisEnabled0;
  uint8_t RTANumEventsActive11;
  uint8_t RTANumEventsActive10;
  uint8_t RTANumEventsActive9;
  uint8_t RTANumEventsActive8;
  uint8_t RTAAnalysisEnabled11;
  uint8_t RTAAnalysisEnabled10;
  uint8_t RTAAnalysisEnabled9;
  uint8_t RTAAnalysisEnabled8;
  uint8_t RTAAnalysisEnabled7;
  uint8_t RTAAnalysisEnabled6;
  uint8_t RTAAnalysisEnabled5;
  uint8_t RTAAnalysisEnabled4;
  uint32_t GRBLastTrigTime;
  uint8_t ShieldNumAlgoTriggers0;
  uint8_t ShieldNumAlgoTriggers1;
  uint8_t ShieldNumAlgoTriggers2;
  uint8_t WhichSIP;
  uint8_t TelemUDPMode;
  uint16_t SIPLon;
  uint16_t SIPLat;
  uint16_t SIPAlt;
  uint32_t SIPTime;
  uint16_t SIPWeek;
  uint16_t SIPPressure;
  uint16_t SIPHealth;
  uint8_t FlightCodeCPUUsage;
  uint8_t FlightCodeMemUsage;
  uint8_t MagredCPUUsage;
  uint8_t MagredMemUsage;
  uint32_t EthernetTotalNumRawDataframes;
  uint32_t EthernetTotalNumComptonDataframes;
  uint8_t DoublePumpOverrideEnabled;
  uint8_t PumpEPromCodeGood;
  uint8_t PumpTachAValid;
  uint8_t PumpTachBValid;
  uint8_t PumpDACASetting;
  uint8_t PumpDACBSetting;
  uint16_t PumpTachALast;
  uint16_t PumpTachAHigh;
  uint16_t PumpTachALow;
  uint16_t PumpTachBLast;
  uint16_t PumpTachBHigh;
  uint16_t PumpTachBLow;
  uint16_t PumpLevelSensor;
  uint8_t ShieldNumSamples;
  uint32_t* NumCounts;
  uint32_t* TimeInterval;
  uint8_t* LiveTimeFraction;
};

struct GCUHousekeepingPacket* MakeNewGCUHousekeepingPacket(void);
struct GCUHousekeepingPacket* ParseGCUHousekeepingPacket(uint8_t* RawData);
void ParseAllocatedGCUHousekeepingPacket(uint8_t* RawData, struct GCUHousekeepingPacket* packet);
void ParseGCUHousekeepingPacketWrapper(uint8_t* RawData, void* packet_bytes);
void printGCUHousekeepingPacket(struct GCUHousekeepingPacket* packet);

#endif
